# Generated by Django 5.1.2 on 2024-10-15 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("product", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DibsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("modifiedAt", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dibGroups",
                        to="user.user",
                    ),
                ),
            ],
            options={
                "db_table": "dibs_group",
                "ordering": ("id",),
                "get_latest_by": "createdAt",
            },
        ),
        migrations.CreateModel(
            name="DibsDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("modifiedAt", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dibsDetails",
                        to="product.product",
                    ),
                ),
                (
                    "dibsGroup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dibsDetails",
                        to="dibs.dibsgroup",
                    ),
                ),
            ],
            options={
                "db_table": "dibs_detail",
                "ordering": ("id",),
                "get_latest_by": "createdAt",
            },
        ),
    ]
